"""Add profile_image to users, remove created_at

Revision ID: 683114cf0fde
Revises: 35092ba27533
Create Date: 2025-06-06 03:34:13.255008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '683114cf0fde'
down_revision: Union[str, None] = '35092ba27533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image', sa.String(length=500), nullable=True))
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.drop_column('users', 'profile_image')
    # ### end Alembic commands ###
